{
 "title": "Our Custom Dashboard",
 "description": "Made from Scratch for ft_transcendence",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "NGINX Server Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"nginx-prometheus-exporter:9113\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DJANGO Server Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"web:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database executions by vendor",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "django_db_execute_total", "legendFormat": "{{instance}} : {{vendor}}" }
   ]
  },
  {
   "title": "NGINX - Active Connections",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_connections_active", "legendFormat": "{{label_name}}" }
   ]
  },
  {
   "title": "Django latency",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "django_http_requests_latency_including_middlewares_seconds_count",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "FD usage - NGINX",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_open_fds / process_max_fds * 100\r\n\r\n",
     "legendFormat": "{{instance}}"
    },
    { "expr": "process_max_fds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "FD usage - Django",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_open_fds / process_max_fds * 100\r\n\r\n",
     "legendFormat": "{{instance}}"
    },
    { "expr": "process_max_fds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Requests by type",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "promhttp_metric_handler_requests_total",
     "legendFormat": "{{job}} : {{code}}"
    }
   ]
  },
  {
   "title": "Nginx total HTTP requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 14 },
   "targets": [
    { "expr": "nginx_http_requests_total", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}