FROM nginx:latest

RUN rm /etc/nginx/conf.d/default.conf

COPY ./default.conf /etc/nginx/conf.d/default.conf

RUN mkdir -p /etc/nginx/ssl

RUN chmod 777 /etc/nginx/ssl

RUN openssl req -newkey rsa:4096 -sha256 -x509 -nodes -days 365 -out /etc/nginx/ssl/sslcert.crt -keyout /etc/nginx/ssl/sslcert.key -subj "/C=CA/ST=Quebec/L=Quebec City/O=42School/OU=42Quebec/CN=transcendence.42.fr"

# EXPOSE 80

# CMD ["nginx", "-g", "daemon off;"]